/**

Generated by the following Solidity interface...
```solidity
interface LibTupler {
    function extractElement(bytes memory tuple, uint256 index) external pure returns (bytes32);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "extractElement",
    "inputs": [
      {
        "name": "tuple",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style,
    clippy::empty_structs_with_brackets
)]
pub mod LibTupler {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    /// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x6080604052348015600e575f5ffd5b506102ab8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c80639bd3b2271461002d575b5f5ffd5b610047600480360381019061004291906101ea565b61005d565b604051610054919061025c565b60405180910390f35b5f60208060018401028401f35b5f604051905090565b5f5ffd5b5f5ffd5b5f5ffd5b5f5ffd5b5f601f19601f8301169050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52604160045260245ffd5b6100c982610083565b810181811067ffffffffffffffff821117156100e8576100e7610093565b5b80604052505050565b5f6100fa61006a565b905061010682826100c0565b919050565b5f67ffffffffffffffff82111561012557610124610093565b5b61012e82610083565b9050602081019050919050565b828183375f83830152505050565b5f61015b6101568461010b565b6100f1565b9050828152602081018484840111156101775761017661007f565b5b61018284828561013b565b509392505050565b5f82601f83011261019e5761019d61007b565b5b81356101ae848260208601610149565b91505092915050565b5f819050919050565b6101c9816101b7565b81146101d3575f5ffd5b50565b5f813590506101e4816101c0565b92915050565b5f5f60408385031215610200576101ff610073565b5b5f83013567ffffffffffffffff81111561021d5761021c610077565b5b6102298582860161018a565b925050602061023a858286016101d6565b9150509250929050565b5f819050919050565b61025681610244565b82525050565b5f60208201905061026f5f83018461024d565b9291505056fea2646970667358221220787c322210ada5eaf02706bd9afdc126e7d7e953317845f681b95f9ce96dad7464736f6c634300081e0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15`\x0EW__\xFD[Pa\x02\xAB\x80a\0\x1C_9_\xF3\xFE`\x80`@R4\x80\x15a\0\x0FW__\xFD[P`\x046\x10a\0)W_5`\xE0\x1C\x80c\x9B\xD3\xB2'\x14a\0-W[__\xFD[a\0G`\x04\x806\x03\x81\x01\x90a\0B\x91\x90a\x01\xEAV[a\0]V[`@Qa\0T\x91\x90a\x02\\V[`@Q\x80\x91\x03\x90\xF3[_` \x80`\x01\x84\x01\x02\x84\x01\xF3[_`@Q\x90P\x90V[__\xFD[__\xFD[__\xFD[__\xFD[_`\x1F\x19`\x1F\x83\x01\x16\x90P\x91\x90PV[\x7FNH{q\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0_R`A`\x04R`$_\xFD[a\0\xC9\x82a\0\x83V[\x81\x01\x81\x81\x10g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x82\x11\x17\x15a\0\xE8Wa\0\xE7a\0\x93V[[\x80`@RPPPV[_a\0\xFAa\0jV[\x90Pa\x01\x06\x82\x82a\0\xC0V[\x91\x90PV[_g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x82\x11\x15a\x01%Wa\x01$a\0\x93V[[a\x01.\x82a\0\x83V[\x90P` \x81\x01\x90P\x91\x90PV[\x82\x81\x837_\x83\x83\x01RPPPV[_a\x01[a\x01V\x84a\x01\x0BV[a\0\xF1V[\x90P\x82\x81R` \x81\x01\x84\x84\x84\x01\x11\x15a\x01wWa\x01va\0\x7FV[[a\x01\x82\x84\x82\x85a\x01;V[P\x93\x92PPPV[_\x82`\x1F\x83\x01\x12a\x01\x9EWa\x01\x9Da\0{V[[\x815a\x01\xAE\x84\x82` \x86\x01a\x01IV[\x91PP\x92\x91PPV[_\x81\x90P\x91\x90PV[a\x01\xC9\x81a\x01\xB7V[\x81\x14a\x01\xD3W__\xFD[PV[_\x815\x90Pa\x01\xE4\x81a\x01\xC0V[\x92\x91PPV[__`@\x83\x85\x03\x12\x15a\x02\0Wa\x01\xFFa\0sV[[_\x83\x015g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x81\x11\x15a\x02\x1DWa\x02\x1Ca\0wV[[a\x02)\x85\x82\x86\x01a\x01\x8AV[\x92PP` a\x02:\x85\x82\x86\x01a\x01\xD6V[\x91PP\x92P\x92\x90PV[_\x81\x90P\x91\x90PV[a\x02V\x81a\x02DV[\x82RPPV[_` \x82\x01\x90Pa\x02o_\x83\x01\x84a\x02MV[\x92\x91PPV\xFE\xA2dipfsX\"\x12 x|2\"\x10\xAD\xA5\xEA\xF0'\x06\xBD\x9A\xFD\xC1&\xE7\xD7\xE9S1xE\xF6\x81\xB9_\x9C\xE9m\xADtdsolcC\0\x08\x1E\x003",
    );
    /// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x608060405234801561000f575f5ffd5b5060043610610029575f3560e01c80639bd3b2271461002d575b5f5ffd5b610047600480360381019061004291906101ea565b61005d565b604051610054919061025c565b60405180910390f35b5f60208060018401028401f35b5f604051905090565b5f5ffd5b5f5ffd5b5f5ffd5b5f5ffd5b5f601f19601f8301169050919050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52604160045260245ffd5b6100c982610083565b810181811067ffffffffffffffff821117156100e8576100e7610093565b5b80604052505050565b5f6100fa61006a565b905061010682826100c0565b919050565b5f67ffffffffffffffff82111561012557610124610093565b5b61012e82610083565b9050602081019050919050565b828183375f83830152505050565b5f61015b6101568461010b565b6100f1565b9050828152602081018484840111156101775761017661007f565b5b61018284828561013b565b509392505050565b5f82601f83011261019e5761019d61007b565b5b81356101ae848260208601610149565b91505092915050565b5f819050919050565b6101c9816101b7565b81146101d3575f5ffd5b50565b5f813590506101e4816101c0565b92915050565b5f5f60408385031215610200576101ff610073565b5b5f83013567ffffffffffffffff81111561021d5761021c610077565b5b6102298582860161018a565b925050602061023a858286016101d6565b9150509250929050565b5f819050919050565b61025681610244565b82525050565b5f60208201905061026f5f83018461024d565b9291505056fea2646970667358221220787c322210ada5eaf02706bd9afdc126e7d7e953317845f681b95f9ce96dad7464736f6c634300081e0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15a\0\x0FW__\xFD[P`\x046\x10a\0)W_5`\xE0\x1C\x80c\x9B\xD3\xB2'\x14a\0-W[__\xFD[a\0G`\x04\x806\x03\x81\x01\x90a\0B\x91\x90a\x01\xEAV[a\0]V[`@Qa\0T\x91\x90a\x02\\V[`@Q\x80\x91\x03\x90\xF3[_` \x80`\x01\x84\x01\x02\x84\x01\xF3[_`@Q\x90P\x90V[__\xFD[__\xFD[__\xFD[__\xFD[_`\x1F\x19`\x1F\x83\x01\x16\x90P\x91\x90PV[\x7FNH{q\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0_R`A`\x04R`$_\xFD[a\0\xC9\x82a\0\x83V[\x81\x01\x81\x81\x10g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x82\x11\x17\x15a\0\xE8Wa\0\xE7a\0\x93V[[\x80`@RPPPV[_a\0\xFAa\0jV[\x90Pa\x01\x06\x82\x82a\0\xC0V[\x91\x90PV[_g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x82\x11\x15a\x01%Wa\x01$a\0\x93V[[a\x01.\x82a\0\x83V[\x90P` \x81\x01\x90P\x91\x90PV[\x82\x81\x837_\x83\x83\x01RPPPV[_a\x01[a\x01V\x84a\x01\x0BV[a\0\xF1V[\x90P\x82\x81R` \x81\x01\x84\x84\x84\x01\x11\x15a\x01wWa\x01va\0\x7FV[[a\x01\x82\x84\x82\x85a\x01;V[P\x93\x92PPPV[_\x82`\x1F\x83\x01\x12a\x01\x9EWa\x01\x9Da\0{V[[\x815a\x01\xAE\x84\x82` \x86\x01a\x01IV[\x91PP\x92\x91PPV[_\x81\x90P\x91\x90PV[a\x01\xC9\x81a\x01\xB7V[\x81\x14a\x01\xD3W__\xFD[PV[_\x815\x90Pa\x01\xE4\x81a\x01\xC0V[\x92\x91PPV[__`@\x83\x85\x03\x12\x15a\x02\0Wa\x01\xFFa\0sV[[_\x83\x015g\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\x81\x11\x15a\x02\x1DWa\x02\x1Ca\0wV[[a\x02)\x85\x82\x86\x01a\x01\x8AV[\x92PP` a\x02:\x85\x82\x86\x01a\x01\xD6V[\x91PP\x92P\x92\x90PV[_\x81\x90P\x91\x90PV[a\x02V\x81a\x02DV[\x82RPPV[_` \x82\x01\x90Pa\x02o_\x83\x01\x84a\x02MV[\x92\x91PPV\xFE\xA2dipfsX\"\x12 x|2\"\x10\xAD\xA5\xEA\xF0'\x06\xBD\x9A\xFD\xC1&\xE7\xD7\xE9S1xE\xF6\x81\xB9_\x9C\xE9m\xADtdsolcC\0\x08\x1E\x003",
    );
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `extractElement(bytes,uint256)` and selector `0x9bd3b227`.
```solidity
function extractElement(bytes memory tuple, uint256 index) external pure returns (bytes32);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct extractElementCall {
        #[allow(missing_docs)]
        pub tuple: alloy::sol_types::private::Bytes,
        #[allow(missing_docs)]
        pub index: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`extractElement(bytes,uint256)`](extractElementCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct extractElementReturn {
        #[allow(missing_docs)]
        pub _0: alloy::sol_types::private::FixedBytes<32>,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Bytes,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Bytes,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<extractElementCall> for UnderlyingRustTuple<'_> {
                fn from(value: extractElementCall) -> Self {
                    (value.tuple, value.index)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for extractElementCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        tuple: tuple.0,
                        index: tuple.1,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::FixedBytes<32>,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<extractElementReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: extractElementReturn) -> Self {
                    (value._0,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for extractElementReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _0: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for extractElementCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::Bytes,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::FixedBytes<32>;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "extractElement(bytes,uint256)";
            const SELECTOR: [u8; 4] = [155u8, 211u8, 178u8, 39u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        &self.tuple,
                    ),
                    <alloy::sol_types::sol_data::Uint<
                        256,
                    > as alloy_sol_types::SolType>::tokenize(&self.index),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::FixedBytes<
                        32,
                    > as alloy_sol_types::SolType>::tokenize(ret),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: extractElementReturn = r.into();
                        r._0
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: extractElementReturn = r.into();
                        r._0
                    })
            }
        }
    };
    ///Container for all the [`LibTupler`](self) function calls.
    #[derive(Clone)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive()]
    pub enum LibTuplerCalls {
        #[allow(missing_docs)]
        extractElement(extractElementCall),
    }
    impl LibTuplerCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] = &[[155u8, 211u8, 178u8, 39u8]];
        /// The names of the variants in the same order as `SELECTORS`.
        pub const VARIANT_NAMES: &'static [&'static str] = &[
            ::core::stringify!(extractElement),
        ];
        /// The signatures in the same order as `SELECTORS`.
        pub const SIGNATURES: &'static [&'static str] = &[
            <extractElementCall as alloy_sol_types::SolCall>::SIGNATURE,
        ];
        /// Returns the signature for the given selector, if known.
        #[inline]
        pub fn signature_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            match Self::SELECTORS.binary_search(&selector) {
                ::core::result::Result::Ok(idx) => {
                    ::core::option::Option::Some(Self::SIGNATURES[idx])
                }
                ::core::result::Result::Err(_) => ::core::option::Option::None,
            }
        }
        /// Returns the enum variant name for the given selector, if known.
        #[inline]
        pub fn name_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            let sig = Self::signature_by_selector(selector)?;
            sig.split_once('(').map(|(name, _)| name)
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for LibTuplerCalls {
        const NAME: &'static str = "LibTuplerCalls";
        const MIN_DATA_LENGTH: usize = 96usize;
        const COUNT: usize = 1usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::extractElement(_) => {
                    <extractElementCall as alloy_sol_types::SolCall>::SELECTOR
                }
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(
                &[u8],
            ) -> alloy_sol_types::Result<LibTuplerCalls>] = &[
                {
                    fn extractElement(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<LibTuplerCalls> {
                        <extractElementCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(LibTuplerCalls::extractElement)
                    }
                    extractElement
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_SHIMS[idx](data)
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw_validate(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_VALIDATE_SHIMS: &[fn(
                &[u8],
            ) -> alloy_sol_types::Result<LibTuplerCalls>] = &[
                {
                    fn extractElement(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<LibTuplerCalls> {
                        <extractElementCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(LibTuplerCalls::extractElement)
                    }
                    extractElement
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_VALIDATE_SHIMS[idx](data)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::extractElement(inner) => {
                    <extractElementCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::extractElement(inner) => {
                    <extractElementCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`LibTupler`](self) contract instance.

See the [wrapper's documentation](`LibTuplerInstance`) for more details.*/
    #[inline]
    pub const fn new<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        __provider: P,
    ) -> LibTuplerInstance<P, N> {
        LibTuplerInstance::<P, N>::new(address, __provider)
    }
    /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
    #[inline]
    pub fn deploy<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        __provider: P,
    ) -> impl ::core::future::Future<
        Output = alloy_contract::Result<LibTuplerInstance<P, N>>,
    > {
        LibTuplerInstance::<P, N>::deploy(__provider)
    }
    /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
    #[inline]
    pub fn deploy_builder<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
        LibTuplerInstance::<P, N>::deploy_builder(__provider)
    }
    /**A [`LibTupler`](self) instance.

Contains type-safe methods for interacting with an on-chain instance of the
[`LibTupler`](self) contract located at a given `address`, using a given
provider `P`.

If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
documentation on how to provide it), the `deploy` and `deploy_builder` methods can
be used to deploy a new instance of the contract.

See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct LibTuplerInstance<P, N = alloy_contract::private::Ethereum> {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network: ::core::marker::PhantomData<N>,
    }
    #[automatically_derived]
    impl<P, N> ::core::fmt::Debug for LibTuplerInstance<P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("LibTuplerInstance").field(&self.address).finish()
        }
    }
    /// Instantiation and getters/setters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > LibTuplerInstance<P, N> {
        /**Creates a new wrapper around an on-chain [`LibTupler`](self) contract instance.

See the [wrapper's documentation](`LibTuplerInstance`) for more details.*/
        #[inline]
        pub const fn new(
            address: alloy_sol_types::private::Address,
            __provider: P,
        ) -> Self {
            Self {
                address,
                provider: __provider,
                _network: ::core::marker::PhantomData,
            }
        }
        /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
        #[inline]
        pub async fn deploy(
            __provider: P,
        ) -> alloy_contract::Result<LibTuplerInstance<P, N>> {
            let call_builder = Self::deploy_builder(__provider);
            let contract_address = call_builder.deploy().await?;
            Ok(Self::new(contract_address, call_builder.provider))
        }
        /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
        #[inline]
        pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
            alloy_contract::RawCallBuilder::new_raw_deploy(
                __provider,
                ::core::clone::Clone::clone(&BYTECODE),
            )
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<P: ::core::clone::Clone, N> LibTuplerInstance<&P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> LibTuplerInstance<P, N> {
            LibTuplerInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > LibTuplerInstance<P, N> {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<&P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`extractElement`] function.
        pub fn extractElement(
            &self,
            tuple: alloy::sol_types::private::Bytes,
            index: alloy::sol_types::private::primitives::aliases::U256,
        ) -> alloy_contract::SolCallBuilder<&P, extractElementCall, N> {
            self.call_builder(&extractElementCall { tuple, index })
        }
    }
    /// Event filters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > LibTuplerInstance<P, N> {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<&P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
    }
}
