/**

Generated by the following Solidity interface...
```solidity
interface MultiReturn {
    event Calculated(uint256 j);

    function intTuple() external pure returns (uint256, uint256, uint256);
    function tupleConsumer(uint256 arg) external;
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "intTuple",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "tupleConsumer",
    "inputs": [
      {
        "name": "arg",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Calculated",
    "inputs": [
      {
        "name": "j",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style,
    clippy::empty_structs_with_brackets
)]
pub mod MultiReturn {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    /// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x6080604052348015600e575f5ffd5b506101ba8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806338271fbf146100385780635bd54e4214610054575b5f5ffd5b610052600480360381019061004d91906100fc565b610074565b005b61005c6100ae565b60405161006b93929190610136565b60405180910390f35b7f2c257d436c72ddfcf6860baf0bde6e7deca235585f3cd5a7e1da579a04c98ab1816040516100a3919061016b565b60405180910390a150565b5f5f5f610bad61deed61cafe925092509250909192565b5f5ffd5b5f819050919050565b6100db816100c9565b81146100e5575f5ffd5b50565b5f813590506100f6816100d2565b92915050565b5f60208284031215610111576101106100c5565b5b5f61011e848285016100e8565b91505092915050565b610130816100c9565b82525050565b5f6060820190506101495f830186610127565b6101566020830185610127565b6101636040830184610127565b949350505050565b5f60208201905061017e5f830184610127565b9291505056fea26469706673582212201a5a804b9072a79562af3d42553426e22a7fd5f64db1f29124e96ae741a74b1464736f6c634300081e0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15`\x0EW__\xFD[Pa\x01\xBA\x80a\0\x1C_9_\xF3\xFE`\x80`@R4\x80\x15a\0\x0FW__\xFD[P`\x046\x10a\x004W_5`\xE0\x1C\x80c8'\x1F\xBF\x14a\08W\x80c[\xD5NB\x14a\0TW[__\xFD[a\0R`\x04\x806\x03\x81\x01\x90a\0M\x91\x90a\0\xFCV[a\0tV[\0[a\0\\a\0\xAEV[`@Qa\0k\x93\x92\x91\x90a\x016V[`@Q\x80\x91\x03\x90\xF3[\x7F,%}Clr\xDD\xFC\xF6\x86\x0B\xAF\x0B\xDEn}\xEC\xA25X_<\xD5\xA7\xE1\xDAW\x9A\x04\xC9\x8A\xB1\x81`@Qa\0\xA3\x91\x90a\x01kV[`@Q\x80\x91\x03\x90\xA1PV[___a\x0B\xADa\xDE\xEDa\xCA\xFE\x92P\x92P\x92P\x90\x91\x92V[__\xFD[_\x81\x90P\x91\x90PV[a\0\xDB\x81a\0\xC9V[\x81\x14a\0\xE5W__\xFD[PV[_\x815\x90Pa\0\xF6\x81a\0\xD2V[\x92\x91PPV[_` \x82\x84\x03\x12\x15a\x01\x11Wa\x01\x10a\0\xC5V[[_a\x01\x1E\x84\x82\x85\x01a\0\xE8V[\x91PP\x92\x91PPV[a\x010\x81a\0\xC9V[\x82RPPV[_``\x82\x01\x90Pa\x01I_\x83\x01\x86a\x01'V[a\x01V` \x83\x01\x85a\x01'V[a\x01c`@\x83\x01\x84a\x01'V[\x94\x93PPPPV[_` \x82\x01\x90Pa\x01~_\x83\x01\x84a\x01'V[\x92\x91PPV\xFE\xA2dipfsX\"\x12 \x1AZ\x80K\x90r\xA7\x95b\xAF=BU4&\xE2*\x7F\xD5\xF6M\xB1\xF2\x91$\xE9j\xE7A\xA7K\x14dsolcC\0\x08\x1E\x003",
    );
    /// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806338271fbf146100385780635bd54e4214610054575b5f5ffd5b610052600480360381019061004d91906100fc565b610074565b005b61005c6100ae565b60405161006b93929190610136565b60405180910390f35b7f2c257d436c72ddfcf6860baf0bde6e7deca235585f3cd5a7e1da579a04c98ab1816040516100a3919061016b565b60405180910390a150565b5f5f5f610bad61deed61cafe925092509250909192565b5f5ffd5b5f819050919050565b6100db816100c9565b81146100e5575f5ffd5b50565b5f813590506100f6816100d2565b92915050565b5f60208284031215610111576101106100c5565b5b5f61011e848285016100e8565b91505092915050565b610130816100c9565b82525050565b5f6060820190506101495f830186610127565b6101566020830185610127565b6101636040830184610127565b949350505050565b5f60208201905061017e5f830184610127565b9291505056fea26469706673582212201a5a804b9072a79562af3d42553426e22a7fd5f64db1f29124e96ae741a74b1464736f6c634300081e0033
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"`\x80`@R4\x80\x15a\0\x0FW__\xFD[P`\x046\x10a\x004W_5`\xE0\x1C\x80c8'\x1F\xBF\x14a\08W\x80c[\xD5NB\x14a\0TW[__\xFD[a\0R`\x04\x806\x03\x81\x01\x90a\0M\x91\x90a\0\xFCV[a\0tV[\0[a\0\\a\0\xAEV[`@Qa\0k\x93\x92\x91\x90a\x016V[`@Q\x80\x91\x03\x90\xF3[\x7F,%}Clr\xDD\xFC\xF6\x86\x0B\xAF\x0B\xDEn}\xEC\xA25X_<\xD5\xA7\xE1\xDAW\x9A\x04\xC9\x8A\xB1\x81`@Qa\0\xA3\x91\x90a\x01kV[`@Q\x80\x91\x03\x90\xA1PV[___a\x0B\xADa\xDE\xEDa\xCA\xFE\x92P\x92P\x92P\x90\x91\x92V[__\xFD[_\x81\x90P\x91\x90PV[a\0\xDB\x81a\0\xC9V[\x81\x14a\0\xE5W__\xFD[PV[_\x815\x90Pa\0\xF6\x81a\0\xD2V[\x92\x91PPV[_` \x82\x84\x03\x12\x15a\x01\x11Wa\x01\x10a\0\xC5V[[_a\x01\x1E\x84\x82\x85\x01a\0\xE8V[\x91PP\x92\x91PPV[a\x010\x81a\0\xC9V[\x82RPPV[_``\x82\x01\x90Pa\x01I_\x83\x01\x86a\x01'V[a\x01V` \x83\x01\x85a\x01'V[a\x01c`@\x83\x01\x84a\x01'V[\x94\x93PPPPV[_` \x82\x01\x90Pa\x01~_\x83\x01\x84a\x01'V[\x92\x91PPV\xFE\xA2dipfsX\"\x12 \x1AZ\x80K\x90r\xA7\x95b\xAF=BU4&\xE2*\x7F\xD5\xF6M\xB1\xF2\x91$\xE9j\xE7A\xA7K\x14dsolcC\0\x08\x1E\x003",
    );
    #[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
    /**Event with signature `Calculated(uint256)` and selector `0x2c257d436c72ddfcf6860baf0bde6e7deca235585f3cd5a7e1da579a04c98ab1`.
    ```solidity
    event Calculated(uint256 j);
    ```*/
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    #[derive(Clone)]
    pub struct Calculated {
        #[allow(missing_docs)]
        pub j: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        #[automatically_derived]
        impl alloy_sol_types::SolEvent for Calculated {
            type DataTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            type DataToken<'a> = <Self::DataTuple<'a> as alloy_sol_types::SolType>::Token<'a>;
            type TopicList = (alloy_sol_types::sol_data::FixedBytes<32>,);
            const SIGNATURE: &'static str = "Calculated(uint256)";
            const SIGNATURE_HASH: alloy_sol_types::private::B256 =
                alloy_sol_types::private::B256::new([
                    44u8, 37u8, 125u8, 67u8, 108u8, 114u8, 221u8, 252u8, 246u8, 134u8, 11u8, 175u8,
                    11u8, 222u8, 110u8, 125u8, 236u8, 162u8, 53u8, 88u8, 95u8, 60u8, 213u8, 167u8,
                    225u8, 218u8, 87u8, 154u8, 4u8, 201u8, 138u8, 177u8,
                ]);
            const ANONYMOUS: bool = false;
            #[allow(unused_variables)]
            #[inline]
            fn new(
                topics: <Self::TopicList as alloy_sol_types::SolType>::RustType,
                data: <Self::DataTuple<'_> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                Self { j: data.0 }
            }
            #[inline]
            fn check_signature(
                topics: &<Self::TopicList as alloy_sol_types::SolType>::RustType,
            ) -> alloy_sol_types::Result<()> {
                if topics.0 != Self::SIGNATURE_HASH {
                    return Err(alloy_sol_types::Error::invalid_event_signature_hash(
                        Self::SIGNATURE,
                        topics.0,
                        Self::SIGNATURE_HASH,
                    ));
                }
                Ok(())
            }
            #[inline]
            fn tokenize_body(&self) -> Self::DataToken<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<256> as alloy_sol_types::SolType>::tokenize(
                        &self.j,
                    ),
                )
            }
            #[inline]
            fn topics(&self) -> <Self::TopicList as alloy_sol_types::SolType>::RustType {
                (Self::SIGNATURE_HASH.into(),)
            }
            #[inline]
            fn encode_topics_raw(
                &self,
                out: &mut [alloy_sol_types::abi::token::WordToken],
            ) -> alloy_sol_types::Result<()> {
                if out.len() < <Self::TopicList as alloy_sol_types::TopicList>::COUNT {
                    return Err(alloy_sol_types::Error::Overrun);
                }
                out[0usize] = alloy_sol_types::abi::token::WordToken(Self::SIGNATURE_HASH);
                Ok(())
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::private::IntoLogData for Calculated {
            fn to_log_data(&self) -> alloy_sol_types::private::LogData {
                From::from(self)
            }
            fn into_log_data(self) -> alloy_sol_types::private::LogData {
                From::from(&self)
            }
        }
        #[automatically_derived]
        impl From<&Calculated> for alloy_sol_types::private::LogData {
            #[inline]
            fn from(this: &Calculated) -> alloy_sol_types::private::LogData {
                alloy_sol_types::SolEvent::encode_log_data(this)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `intTuple()` and selector `0x5bd54e42`.
    ```solidity
    function intTuple() external pure returns (uint256, uint256, uint256);
    ```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct intTupleCall;
    #[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`intTuple()`](intTupleCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct intTupleReturn {
        #[allow(missing_docs)]
        pub _0: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _1: alloy::sol_types::private::primitives::aliases::U256,
        #[allow(missing_docs)]
        pub _2: alloy::sol_types::private::primitives::aliases::U256,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<intTupleCall> for UnderlyingRustTuple<'_> {
                fn from(value: intTupleCall) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for intTupleCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Uint<256>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::primitives::aliases::U256,
                alloy::sol_types::private::primitives::aliases::U256,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<intTupleReturn> for UnderlyingRustTuple<'_> {
                fn from(value: intTupleReturn) -> Self {
                    (value._0, value._1, value._2)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for intTupleReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        _0: tuple.0,
                        _1: tuple.1,
                        _2: tuple.2,
                    }
                }
            }
        }
        impl intTupleReturn {
            fn _tokenize(&self) -> <intTupleCall as alloy_sol_types::SolCall>::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<256> as alloy_sol_types::SolType>::tokenize(
                        &self._0,
                    ),
                    <alloy::sol_types::sol_data::Uint<256> as alloy_sol_types::SolType>::tokenize(
                        &self._1,
                    ),
                    <alloy::sol_types::sol_data::Uint<256> as alloy_sol_types::SolType>::tokenize(
                        &self._2,
                    ),
                )
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for intTupleCall {
            type Parameters<'a> = ();
            type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
            type Return = intTupleReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Uint<256>,
                alloy::sol_types::sol_data::Uint<256>,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<'a> as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "intTuple()";
            const SELECTOR: [u8; 4] = [91u8, 213u8, 78u8, 66u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                ()
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                intTupleReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(
                    data,
                )
                .map(Into::into)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize, Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `tupleConsumer(uint256)` and selector `0x38271fbf`.
    ```solidity
    function tupleConsumer(uint256 arg) external;
    ```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct tupleConsumerCall {
        #[allow(missing_docs)]
        pub arg: alloy::sol_types::private::primitives::aliases::U256,
    }
    ///Container type for the return parameters of the [`tupleConsumer(uint256)`](tupleConsumerCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct tupleConsumerReturn {}
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::primitives::aliases::U256,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<tupleConsumerCall> for UnderlyingRustTuple<'_> {
                fn from(value: tupleConsumerCall) -> Self {
                    (value.arg,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for tupleConsumerCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { arg: tuple.0 }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = ();
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = ();
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(_t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<tupleConsumerReturn> for UnderlyingRustTuple<'_> {
                fn from(value: tupleConsumerReturn) -> Self {
                    ()
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for tupleConsumerReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {}
                }
            }
        }
        impl tupleConsumerReturn {
            fn _tokenize(
                &self,
            ) -> <tupleConsumerCall as alloy_sol_types::SolCall>::ReturnToken<'_> {
                ()
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for tupleConsumerCall {
            type Parameters<'a> = (alloy::sol_types::sol_data::Uint<256>,);
            type Token<'a> = <Self::Parameters<'a> as alloy_sol_types::SolType>::Token<'a>;
            type Return = tupleConsumerReturn;
            type ReturnTuple<'a> = ();
            type ReturnToken<'a> = <Self::ReturnTuple<'a> as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "tupleConsumer(uint256)";
            const SELECTOR: [u8; 4] = [56u8, 39u8, 31u8, 191u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::Uint<256> as alloy_sol_types::SolType>::tokenize(
                        &self.arg,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                tupleConsumerReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<'_> as alloy_sol_types::SolType>::abi_decode_sequence_validate(
                    data,
                )
                .map(Into::into)
            }
        }
    };
    ///Container for all the [`MultiReturn`](self) function calls.
    #[derive(Clone, serde::Serialize, serde::Deserialize)]
    pub enum MultiReturnCalls {
        #[allow(missing_docs)]
        intTuple(intTupleCall),
        #[allow(missing_docs)]
        tupleConsumer(tupleConsumerCall),
    }
    impl MultiReturnCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] =
            &[[56u8, 39u8, 31u8, 191u8], [91u8, 213u8, 78u8, 66u8]];
        /// The names of the variants in the same order as `SELECTORS`.
        pub const VARIANT_NAMES: &'static [&'static str] = &[
            ::core::stringify!(tupleConsumer),
            ::core::stringify!(intTuple),
        ];
        /// The signatures in the same order as `SELECTORS`.
        pub const SIGNATURES: &'static [&'static str] = &[
            <tupleConsumerCall as alloy_sol_types::SolCall>::SIGNATURE,
            <intTupleCall as alloy_sol_types::SolCall>::SIGNATURE,
        ];
        /// Returns the signature for the given selector, if known.
        #[inline]
        pub fn signature_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            match Self::SELECTORS.binary_search(&selector) {
                ::core::result::Result::Ok(idx) => {
                    ::core::option::Option::Some(Self::SIGNATURES[idx])
                }
                ::core::result::Result::Err(_) => ::core::option::Option::None,
            }
        }
        /// Returns the enum variant name for the given selector, if known.
        #[inline]
        pub fn name_by_selector(selector: [u8; 4usize]) -> ::core::option::Option<&'static str> {
            let sig = Self::signature_by_selector(selector)?;
            sig.split_once('(').map(|(name, _)| name)
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for MultiReturnCalls {
        const NAME: &'static str = "MultiReturnCalls";
        const MIN_DATA_LENGTH: usize = 0usize;
        const COUNT: usize = 2usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::intTuple(_) => <intTupleCall as alloy_sol_types::SolCall>::SELECTOR,
                Self::tupleConsumer(_) => <tupleConsumerCall as alloy_sol_types::SolCall>::SELECTOR,
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw(selector: [u8; 4], data: &[u8]) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<MultiReturnCalls>] = &[
                {
                    fn tupleConsumer(data: &[u8]) -> alloy_sol_types::Result<MultiReturnCalls> {
                        <tupleConsumerCall as alloy_sol_types::SolCall>::abi_decode_raw(data)
                            .map(MultiReturnCalls::tupleConsumer)
                    }
                    tupleConsumer
                },
                {
                    fn intTuple(data: &[u8]) -> alloy_sol_types::Result<MultiReturnCalls> {
                        <intTupleCall as alloy_sol_types::SolCall>::abi_decode_raw(data)
                            .map(MultiReturnCalls::intTuple)
                    }
                    intTuple
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(alloy_sol_types::Error::unknown_selector(
                    <Self as alloy_sol_types::SolInterface>::NAME,
                    selector,
                ));
            };
            DECODE_SHIMS[idx](data)
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw_validate(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_VALIDATE_SHIMS: &[fn(
                &[u8],
            )
                -> alloy_sol_types::Result<MultiReturnCalls>] = &[
                {
                    fn tupleConsumer(data: &[u8]) -> alloy_sol_types::Result<MultiReturnCalls> {
                        <tupleConsumerCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                            data,
                        )
                        .map(MultiReturnCalls::tupleConsumer)
                    }
                    tupleConsumer
                },
                {
                    fn intTuple(data: &[u8]) -> alloy_sol_types::Result<MultiReturnCalls> {
                        <intTupleCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(data)
                            .map(MultiReturnCalls::intTuple)
                    }
                    intTuple
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(alloy_sol_types::Error::unknown_selector(
                    <Self as alloy_sol_types::SolInterface>::NAME,
                    selector,
                ));
            };
            DECODE_VALIDATE_SHIMS[idx](data)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::intTuple(inner) => {
                    <intTupleCall as alloy_sol_types::SolCall>::abi_encoded_size(inner)
                }
                Self::tupleConsumer(inner) => {
                    <tupleConsumerCall as alloy_sol_types::SolCall>::abi_encoded_size(inner)
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::intTuple(inner) => {
                    <intTupleCall as alloy_sol_types::SolCall>::abi_encode_raw(inner, out)
                }
                Self::tupleConsumer(inner) => {
                    <tupleConsumerCall as alloy_sol_types::SolCall>::abi_encode_raw(inner, out)
                }
            }
        }
    }
    ///Container for all the [`MultiReturn`](self) events.
    #[derive(Clone, serde::Serialize, serde::Deserialize, Debug, PartialEq, Eq, Hash)]
    pub enum MultiReturnEvents {
        #[allow(missing_docs)]
        Calculated(Calculated),
    }
    impl MultiReturnEvents {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 32usize]] = &[[
            44u8, 37u8, 125u8, 67u8, 108u8, 114u8, 221u8, 252u8, 246u8, 134u8, 11u8, 175u8, 11u8,
            222u8, 110u8, 125u8, 236u8, 162u8, 53u8, 88u8, 95u8, 60u8, 213u8, 167u8, 225u8, 218u8,
            87u8, 154u8, 4u8, 201u8, 138u8, 177u8,
        ]];
        /// The names of the variants in the same order as `SELECTORS`.
        pub const VARIANT_NAMES: &'static [&'static str] = &[::core::stringify!(Calculated)];
        /// The signatures in the same order as `SELECTORS`.
        pub const SIGNATURES: &'static [&'static str] =
            &[<Calculated as alloy_sol_types::SolEvent>::SIGNATURE];
        /// Returns the signature for the given selector, if known.
        #[inline]
        pub fn signature_by_selector(
            selector: [u8; 32usize],
        ) -> ::core::option::Option<&'static str> {
            match Self::SELECTORS.binary_search(&selector) {
                ::core::result::Result::Ok(idx) => {
                    ::core::option::Option::Some(Self::SIGNATURES[idx])
                }
                ::core::result::Result::Err(_) => ::core::option::Option::None,
            }
        }
        /// Returns the enum variant name for the given selector, if known.
        #[inline]
        pub fn name_by_selector(selector: [u8; 32usize]) -> ::core::option::Option<&'static str> {
            let sig = Self::signature_by_selector(selector)?;
            sig.split_once('(').map(|(name, _)| name)
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::SolEventInterface for MultiReturnEvents {
        const NAME: &'static str = "MultiReturnEvents";
        const COUNT: usize = 1usize;
        fn decode_raw_log(
            topics: &[alloy_sol_types::Word],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            match topics.first().copied() {
                Some(<Calculated as alloy_sol_types::SolEvent>::SIGNATURE_HASH) => {
                    <Calculated as alloy_sol_types::SolEvent>::decode_raw_log(topics, data)
                        .map(Self::Calculated)
                }
                _ => alloy_sol_types::private::Err(alloy_sol_types::Error::InvalidLog {
                    name: <Self as alloy_sol_types::SolEventInterface>::NAME,
                    log: alloy_sol_types::private::Box::new(
                        alloy_sol_types::private::LogData::new_unchecked(
                            topics.to_vec(),
                            data.to_vec().into(),
                        ),
                    ),
                }),
            }
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::private::IntoLogData for MultiReturnEvents {
        fn to_log_data(&self) -> alloy_sol_types::private::LogData {
            match self {
                Self::Calculated(inner) => {
                    alloy_sol_types::private::IntoLogData::to_log_data(inner)
                }
            }
        }
        fn into_log_data(self) -> alloy_sol_types::private::LogData {
            match self {
                Self::Calculated(inner) => {
                    alloy_sol_types::private::IntoLogData::into_log_data(inner)
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`MultiReturn`](self) contract instance.

    See the [wrapper's documentation](`MultiReturnInstance`) for more details.*/
    #[inline]
    pub const fn new<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        __provider: P,
    ) -> MultiReturnInstance<P, N> {
        MultiReturnInstance::<P, N>::new(address, __provider)
    }
    /**Deploys this contract using the given `provider` and constructor arguments, if any.

    Returns a new instance of the contract, if the deployment was successful.

    For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
    #[inline]
    pub fn deploy<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>(
        __provider: P,
    ) -> impl ::core::future::Future<Output = alloy_contract::Result<MultiReturnInstance<P, N>>>
    {
        MultiReturnInstance::<P, N>::deploy(__provider)
    }
    /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
    and constructor arguments, if any.

    This is a simple wrapper around creating a `RawCallBuilder` with the data set to
    the bytecode concatenated with the constructor's ABI-encoded arguments.*/
    #[inline]
    pub fn deploy_builder<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        __provider: P,
    ) -> alloy_contract::RawCallBuilder<P, N> {
        MultiReturnInstance::<P, N>::deploy_builder(__provider)
    }
    /**A [`MultiReturn`](self) instance.

    Contains type-safe methods for interacting with an on-chain instance of the
    [`MultiReturn`](self) contract located at a given `address`, using a given
    provider `P`.

    If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
    documentation on how to provide it), the `deploy` and `deploy_builder` methods can
    be used to deploy a new instance of the contract.

    See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct MultiReturnInstance<P, N = alloy_contract::private::Ethereum> {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network: ::core::marker::PhantomData<N>,
    }
    #[automatically_derived]
    impl<P, N> ::core::fmt::Debug for MultiReturnInstance<P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("MultiReturnInstance")
                .field(&self.address)
                .finish()
        }
    }
    /// Instantiation and getters/setters.
    impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>
        MultiReturnInstance<P, N>
    {
        /**Creates a new wrapper around an on-chain [`MultiReturn`](self) contract instance.

        See the [wrapper's documentation](`MultiReturnInstance`) for more details.*/
        #[inline]
        pub const fn new(address: alloy_sol_types::private::Address, __provider: P) -> Self {
            Self {
                address,
                provider: __provider,
                _network: ::core::marker::PhantomData,
            }
        }
        /**Deploys this contract using the given `provider` and constructor arguments, if any.

        Returns a new instance of the contract, if the deployment was successful.

        For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
        #[inline]
        pub async fn deploy(__provider: P) -> alloy_contract::Result<MultiReturnInstance<P, N>> {
            let call_builder = Self::deploy_builder(__provider);
            let contract_address = call_builder.deploy().await?;
            Ok(Self::new(contract_address, call_builder.provider))
        }
        /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
        and constructor arguments, if any.

        This is a simple wrapper around creating a `RawCallBuilder` with the data set to
        the bytecode concatenated with the constructor's ABI-encoded arguments.*/
        #[inline]
        pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
            alloy_contract::RawCallBuilder::new_raw_deploy(
                __provider,
                ::core::clone::Clone::clone(&BYTECODE),
            )
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<P: ::core::clone::Clone, N> MultiReturnInstance<&P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> MultiReturnInstance<P, N> {
            MultiReturnInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>
        MultiReturnInstance<P, N>
    {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<&P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`intTuple`] function.
        pub fn intTuple(&self) -> alloy_contract::SolCallBuilder<&P, intTupleCall, N> {
            self.call_builder(&intTupleCall)
        }
        ///Creates a new call builder for the [`tupleConsumer`] function.
        pub fn tupleConsumer(
            &self,
            arg: alloy::sol_types::private::primitives::aliases::U256,
        ) -> alloy_contract::SolCallBuilder<&P, tupleConsumerCall, N> {
            self.call_builder(&tupleConsumerCall { arg })
        }
    }
    /// Event filters.
    impl<P: alloy_contract::private::Provider<N>, N: alloy_contract::private::Network>
        MultiReturnInstance<P, N>
    {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<&P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
        ///Creates a new event filter for the [`Calculated`] event.
        pub fn Calculated_filter(&self) -> alloy_contract::Event<&P, Calculated, N> {
            self.event_filter::<Calculated>()
        }
    }
}
